test:
    name: identitychaincode1-benchmark
    description: test benchmark
    workers:
      type: local
      number: 2
    rounds:
      - label: identitychaincode1 test
        description: identitychaincode1 benchmark
        txDuration: 60
        rateControl: 
          type: fixed-load
          opts:
            transactionLoad: 300
        workload:
          module: /hyperledger/caliper/workspace/app/callback/app.js
          arguments:
            contractId: identitychaincode1
            randomSeed: 5000000
            userID: Admin@org1.digiprism.com
