---
OrdererOrgs:
  - Name: digiprism.com
    Domain: digiprism.com
    Specs:
      - Hostname: orderer1
        SANS:
          - 192.168.86.33
      - Hostname: orderer2
        SANS:
          - 192.168.86.33
      - Hostname: orderer3
        SANS:
          - 192.168.86.33

PeerOrgs:
  - Name: org1.digiprism.com
    Domain: org1.digiprism.com
    EnableNodeOUs: true
    CA:
      Hostname: ca1
      CommonName: ca1.org1.digiprism.com
      Country: US
      Province: North Carolina
      Locality: Raleigh
    Specs:
      - Hostname: peer1
        CommonName: peer1.org1.digiprism.com
        SANS:
          - 192.168.86.33
      - Hostname: peer2
        CommonName: peer2.org1.digiprism.com
        SANS:
          - 192.168.86.33
  - Name: org2.digiprism.com
    Domain: org2.digiprism.com
    EnableNodeOUs: true
    CA:
      Hostname: ca1
      CommonName: ca1.org2.digiprism.com
      Country: US
      Province: North Carolina
      Locality: Raleigh
    Specs:
      - Hostname: peer1
        CommonName: peer1.org2.digiprism.com
        SANS:
          - 192.168.86.33
      - Hostname: peer2
        CommonName: peer2.org2.digiprism.com
        SANS:
          - 192.168.86.33
  - Name: org3.digiprism.com
    Domain: org3.digiprism.com
    EnableNodeOUs: true
    CA:
      Hostname: ca1
      CommonName: ca1.org3.digiprism.com
      Country: US
      Province: North Carolina
      Locality: Raleigh
    Specs:
      - Hostname: peer1
        CommonName: peer1.org3.digiprism.com
        SANS:
          - 192.168.86.33
      - Hostname: peer2
        CommonName: peer2.org3.digiprism.com
        SANS:
          - 192.168.86.33
