test:
    name: identitychaincode2-benchmark
    description: test benchmark
    workers:
      type: local
      number: 2
    rounds:
      - label: identitychaincode2 test
        description: identitychaincode2 benchmark
        txDuration: 60
        rateControl: 
          type: fixed-load
          opts:
            transactionLoad: 300
        workload:
          module: /hyperledger/caliper/workspace/app/callback/app.js
          arguments:
            contractId: identitychaincode2
            randomSeed: 5000000
            userID: Admin@org1.identity.com
